version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1
  aws-cli: circleci/aws-cli@4.1.1


commands:
  destroy-environment:
    description: Delete cluster
    parameters:
      # Add parameter here   
    steps:
      - run:
          name: Delete Cluster
          when: on_fail
          command: |
            # Your code here
            aws cloudformation delete-stack --stack-name eksctl-capstone-project-cluster
            eksctl delete cluster --region=us-east-1 --name=capstone-project


jobs:
  build-app:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Linting
          command: pylint app.py


  build-and-push-docker-image:
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            sh ./run_docker.sh
      - run:
          name: Push Docker image to Docker Hub
          command: |
            sh ./upload_docker.sh


  create-cluster:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - run:
            name: Install tar and gzip
            command: |
              apk add --update tar gzip nodejs npm curl  
        - run:
            name: install_awscli
            command: |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              ./aws/install 
        - run:
            name: install_aws_eks
            command: |
              mkdir -p src
              curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C src
              chmod +x src/eksctl
              SUDO=""
              if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
                  SUDO="sudo"
              fi
                  $SUDO mv src/eksctl /usr/local/bin/
                  rmdir src
        - run:
            name: install_kubectl
            command: |
              curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
              kubectl version --client
        - run:
            name: AWS EKS cluster creation
            command: |
              eksctl create cluster --name capstone-project --region us-east-1 --zones us-east-1a,us-east-1b,us-east-1c,us-east-1d 
#        - run:
#            name: Introduced Delay
#            command: |
#              sleep 60
        - run:
            name: AWS EKS get cluster creation
            command: |
              eksctl utils describe-stacks --region us-east-1 --cluster capstone-project
              eksctl get cluster --name capstone-project --region us-east-1
        - destroy-environment



  deploy-over-kubernetes:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y unzip
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      # Install kubectl
      - run:
          name: Install kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl

      # Install eksctl
      - run:
          name: Install eksctl
          command: |
            sudo apt-get update && sudo apt-get install -y curl
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin

      - run:
          name: Deploy to EKS
          command: |
            aws eks update-kubeconfig --name capstone-project --region us-east-1
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
            sleep 30
            kubectl get deploy,rs,svc,pods,nodes,services
      - destroy-environment


workflows:
  default:
    jobs:
      - build-app
      #- build-and-push-docker-image:
      #    requires: [build-app]
      #- create-cluster:
      #    requires: [build-and-push-docker-image]
      #- deploy-over-kubernetes:
      #    requires: [create-cluster]